name: Docker Build and Publish
on:
  push:
    branches:
      - main  # Run workflow on push to main branch
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract build number
        id: build_number
        run: |
          echo "BUILD_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "IMAGE_TAG=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ldp-api-identity:${{ env.IMAGE_TAG }} -f src/Dockerfile src/
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ldp-api-identity:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/ldp-api-identity:latest
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ldp-api-identity:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ldp-api-identity:latest